name: fatigue_guard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  flutter_tts: ^4.2.2  # Voice text-to-speech plugin for voice warning announcements
  image_picker: ^1.1.2  # Used for selecting images from phone gallery
  url_launcher: ^6.2.5 # Used for launching external URLs (Google Maps for navigation)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/baby.jpeg